on: push
jobs:
    lhci:
        name: Lighthouse
        runs-on: ubuntu-22.04
        steps:
            -   uses: actions/checkout@v4
            -   name: Use Node.js 18.x
                uses: actions/setup-node@v3
                with:
                    node-version: 18.x
            -   name: npm install, build
                run: |
                    npm install
            -   name: run Lighthouse CI
                run: |
                    echo "npx lhci autorun"
                    echo "disabled due to unactionable Lighthouse failure"
